import { Report, User } from '@/types'

interface ReportsListProps {
  reports: Report[]
}

export default function ReportsList({ reports }: ReportsListProps) {
  if (reports.length === 0) {
    return (
      <div className="bg-white rounded-lg shadow-lg p-8 text-center">
        <div className="text-gray-400 text-4xl mb-2">📊</div>
        <p className="text-gray-600">No reports generated yet</p>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {reports.map((report) => {
        const generatedBy = report.metadata.generated_by as User | undefined

        return (
          <div key={report.id} className="bg-white rounded-lg shadow-lg p-6">
            <div className="flex items-start justify-between mb-4">
              <div>
                <div className="flex items-center gap-3 mb-2">
                  <h3 className="text-xl font-bold text-gray-900">{report.title}</h3>
                  <span className={`px-3 py-1 rounded-full text-xs font-medium ${
                    report.metadata.report_type.value === 'Weekly'
                      ? 'bg-blue-100 text-blue-700'
                      : 'bg-purple-100 text-purple-700'
                  }`}>
                    {report.metadata.report_type.value}
                  </span>
                </div>
                <p className="text-sm text-gray-600">
                  {report.metadata.start_date} to {report.metadata.end_date}
                </p>
              </div>
              <div className="text-center">
                <div className="text-3xl font-bold text-blue-600">{report.metadata.overall_score}%</div>
                <div className="text-xs text-gray-600">Overall Score</div>
              </div>
            </div>

            <div className="grid grid-cols-4 gap-4 mb-6">
              <div className="text-center p-3 bg-gray-50 rounded-lg">
                <div className="text-2xl font-bold text-gray-900">{report.metadata.total_tasks_assigned}</div>
                <div className="text-xs text-gray-600">Total Assigned</div>
              </div>
              <div className="text-center p-3 bg-green-50 rounded-lg">
                <div className="text-2xl font-bold text-green-600">{report.metadata.tasks_completed}</div>
                <div className="text-xs text-green-700">Completed</div>
              </div>
              <div className="text-center p-3 bg-yellow-50 rounded-lg">
                <div className="text-2xl font-bold text-yellow-600">{report.metadata.tasks_pending}</div>
                <div className="text-xs text-yellow-700">Pending</div>
              </div>
              <div className="text-center p-3 bg-red-50 rounded-lg">
                <div className="text-2xl font-bold text-red-600">{report.metadata.tasks_failed}</div>
                <div className="text-xs text-red-700">Failed</div>
              </div>
            </div>

            {report.metadata.ai_suggestions && (
              <div className="mb-4 p-4 bg-indigo-50 border border-indigo-200 rounded-lg">
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-lg">🤖</span>
                  <h4 className="font-medium text-indigo-900">AI Improvement Suggestions</h4>
                </div>
                <p className="text-sm text-indigo-700 whitespace-pre-line">{report.metadata.ai_suggestions}</p>
              </div>
            )}

            {generatedBy && (
              <div className="pt-4 border-t border-gray-200 text-sm text-gray-600">
                <span className="font-medium">Generated by:</span> {generatedBy.metadata.full_name}
              </div>
            )}
          </div>
        )
      })}
    </div>
  )
}